<!DOCTYPE html>
<html >
<head>
    <meta charset="UTF-8">
    <title>Login</title>

    <link rel="stylesheet" href="../Styles/chat.css?v=<?php echo time();?>">
    <link rel="stylesheet" href="../Styles/menuButtonStyle.css?v=<?php echo time();?>">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
<!--    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>-->
    <script src="../JS/jquery-3.1.1.min.js"></script>
</head>


<body class="single-chat-body">
<div class="chat-title">
    <a href="chats.php">
        <img class="chat-back-arrow" src="../img/imgs/back.png">
    </a>
    <a href="userInfo.php?username=<?php echo $interlocutor->username; ?>" >
        <img class="chat-avatar" src="<?php echo $interlocutor->image; ?>">
        <span class="chat-user-info"><?php echo $interlocutor->getName(); ?>
            <br>
            <span class="chat-status">
                <?php echo $interlocutor->status; ?>
            </span>
        </span>
    </a>
</div>
<div class="chat-story-area" id="chat">
<!--    <div class="chat-user-bubble">-->
<!--        <span class="chats-message">Hi!</span>-->
<!--    </div>-->
<!--    <div class="chat-me-bubble">-->
<!--        <span class="chats-message">Wow</span>-->
<!--    </div>-->
<!--    <div class="chat-user-bubble">-->
<!--        <span class="chats-message">How are you?</span>-->
<!--    </div>-->
<!--    <div class="chat-me-bubble">-->
<!--        <span class="chats-message">DDD</span>-->
<!--    </div>-->
</div>



<div class="chat-msg-box">
    <form id="form" action="javascript:void(0);" onsubmit="return sendMessage(this);">
        <input type="text" class="chat-send-input" placeholder="Type message..." name="text">
        <input type="hidden" name="myUid" value="<?php echo $userFor->uid; ?>">
        <input type="hidden" name="partUid" value="<?php echo $interlocutor->uid;?>">
        <button type="submit" class="chat-send-button">Send</button>
    </form>
</div>
</body>
<script src="../JS/chat.js"></script>
</html>