<?php
    if ( !isset($founded) ) {
        die("Not set \$founded");
    }
?>

<!DOCTYPE html>
<html >
<head>
    <meta charset="UTF-8">
    <title>All Chats</title>

    <link rel="stylesheet" href="../Styles/chats.css">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
</head>
<body class="body-chats">
<div id="header">

    <div style="margin-top: 2vh" id="nav-icon2" onclick="openNav()">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
    </div>
    <img  id="chats-find" src="../img/imgs/find.png" onclick="openFindNav()">
</div>


<?php
    //depends on count of exists chats displaying different info
    if ( count($founded) != 0 ) {
        foreach ($founded as $usr) {
            $last = $usr->lastMessage();

            $classMessage = "last-msg-readed";
            if( $usr->howMuchUnread() != 0) {
                $classMessage = "last-msg-not-readed";
            }
            $date = $usr->lastMessageDate();
            $status = "Busy";
            $statusClass = "chats-status-doNotDisturb";
            $name = $usr->interlocutor->getName();
            $img = ( isset($usr->interlocutor->image) )?  $usr->interlocutor->image : "/img/space-for-avatar.png";
            $img2 = ( isset($usr->me->image) )?  $usr->me->image : "/img/space-for-avatar.png";

            $out = "";
            if ( $usr->lastMessageSenderId() == $usr->me->uid) {
                $out = "<img class=\"chats-sended\" class=\"chats-status-doNotDisturb\" src=\"$img2\">";
            }

            echo "<a href='chat.php?user=".$usr->interlocutor->username."'>".
                "<div class=\"chats-user\">".
    "<img class=\"chats-photo\" src=\"$img\">".
    "<div style=\"background-color: #69F0AE;\" class=\"chats-status-doNotDisturb\">".
    "</div>".
    "<div class=\"chat-head\">".
        "<span class=\"chat-time-position\">$date</span>".
        "<span class=\"chat-status\">$status</span>".
    "</div>".
    "<div class=\"chats-name-last-msg\">".

        "<span id=\"name\">$name</span>".
    "</div>".
    "<div class=\"$classMessage\">".
        $out.
        "<span class=\"chats-msg-pos\">$last</span>".
    "</div>".
"</div>".
                "</a>";
        }
    }
    ?>



<?php include "./View/menuContent.phtml"; ?>
<script src="../JS/jgestures.js"></script>
<script src="../JS/menuAnimationAndSwipes.js<?php echo "?v=".time();?>>"></script>
<div id="myFindSidenav" class="find-sidenav">
    <a href="javascript:void(0)" class="closebtn" onclick="closeFindNav()">&times;</a>
    <input class="chats-find-search" type="text" placeholder="Search Name" id="search" onchange="find()">
    <script src="../JS/search.js"></script>

</div>
</body>
</html>