<!DOCTYPE html>
<html >
<head>
  <meta charset="UTF-8">
  <title>Login</title>
  <link rel="stylesheet" href="../Styles/style.css?v=<?php echo time(); ?>">
</head>

<body>
  <div class="cont">
  <div class="demo">
    <div class="login">
        <form action="login.php" name="signIn"  method="post" enctype="multipart/form-data">
          <div class="login__form">
            <div class="login__row">
              <svg class="login__icon name svg-icon" viewBox="0 0 20 20">
                <path d="M0,20 a10,8 0 0,1 20,0z M10,0 a4,4 0 0,1 0,8 a4,4 0 0,1 0,-8" />
              </svg>
              <input type="text" name="username" class="login__input name" placeholder="Username"/>
            </div>
            <div class="login__row">
              <svg class="login__icon pass svg-icon" viewBox="0 0 20 20">
                <path d="M0,20 20,20 20,8 0,8z M10,13 10,16z M4,8 a6,8 0 0,1 12,0" />
              </svg>
              <input type="password" name="password"  class="login__input pass" placeholder="Password"/>
            </div>
            <input type="submit" class="login__submit">Sign in</input>
            <p class="login__signup">Don't have an account? &nbsp;<a href="signup.php">Sign up</a></p>
          </div>
        </form>
    </div>
	  </div>
	</div>
      


    

</body>
</html>
