<!DOCTYPE html>
<html >
<head>
    <meta charset="UTF-8">
    <title>Login</title>

    <link rel="stylesheet" href="../Styles/profile.css?v=<?php echo time(); ?>">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <!--    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>-->
    <script type="text/javascript" src="JS/jquery-1.4.4.min.js"></script>
    <!--    <script type="text/javascript" src="JS/jquery-3.1.1.min.js"></script>-->


</head>


<body>
<div class="background" style="background-image : url(<?php if ( isset($userForeign->image) ) {echo $userForeign->image;} else {echo "img/space-for-avatar.png";} ?>),-webkit-linear-gradient(top,rgba(125,185,232,0)0%,rgba(0,185,232,0)0%, rgba(30,87,153,1)  120%);">
    <div class="info">
        <h2><?php echo $userForeign->getName(); ?><div class="status"><?php echo $userForeign->status; ?></div></h2>
    </div>

    <div menu-pos>
        <div id="nav-icon2" onclick="openNav()">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
        </div>


        <?php
        $threeDots =  "<img onclick=\"openMaNav()\" class=\"more-actions\" src=\"../img/imgs/more-actions.png\" />";
        if ( isset($foreign)) { echo $threeDots; }
        ?>

    </div>
</div>

<?php include "./View/menuContent.phtml"; ?>

<?php
$s = "Add to friends";
$remove = false;
if ( isset($friend)) {
    $s = "Remove from friends";
    $remove = true;
}
$username = $userForeign->username;
$srt = "<div id=\"ma-mySidenav\" class=\"ma-sidenav\">".
    "<a class=\"ma-closebtn\" onclick=\"closeMaNav()\">&times;</a>".
    ".<div class=\"pos1\">".
    "<h1 class=\"more-actions-text\" onclick=\"alert(1);\">".$s."</h1>".
    "<h1 class=\"more-actions-text\">Write message</h1>".
    "<h1 class=\"more-actions-text\">About ".$username."</h1>".
    "<h1 class=\"more-actions-text\">Add to Black List</h1>".
    "</div></div>";

if ( isset($foreign) ) {
    echo $srt;
}
?>

<script src="../JS/jgestures.js"></script>
<script src="../JS/menuAnimationAndSwipes.js"></script>
</body>
</html>