<!--

<!Doctype html>

<head>
    <title>Profile</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="Styles/base.css?v=<?php echo time();?>">
    <link rel="stylesheet" href="Styles/profile.css?v=<?php echo time();?>">

    <script type="text/javascript" src="JS/jquery-1.4.4.min.js"></script>
    <script type="text/javascript" src="JS/jgestures.js"></script>
    <script type="text/javascript">
        $(function(){
            $('body').bind('swiperight', function(){
                var el = document.getElementById("menu");
                var title = document.getElementById("title");
                var dash = document.getElementById("dash");
                var dashes = document.getElementById("alone");

                el.style.display = 'inline';
                el.style.animation= 'moveforward 0.3s';
                el.style.webkitAnimationTimingFunction = 'ease-in';
                el.style.webkitAnimation = 'moveforward 0.3s';

                dash.style.animation= 'moveforward-dash 0.3s';
                dash.style.webkitAnimationTimingFunction = 'ease-in';
                dash.style.webkitAnimation = 'moveforward-dash 0.3s';

                title.style.animation= 'moveforward-title 0.3s';
                title.style.webkitAnimationTimingFunction = 'ease-in';
                title.style.webkitAnimation = 'moveforward-title 0.3s';

                dashes.className = "open";

                dash.style.left = '45vw';

                title.style.left = '61vw';
            });
        });
        $(function(){
            $('body').bind('swipeleft', function(){
                var el = document.getElementById("menu");
                var title = document.getElementById("title");
                var dash = document.getElementById("dash");
                var dashes = document.getElementById("alone");

                if ( el.style.display == "none") {
                    return ;
                }

                el.style.animation= 'moveback 0.3s';
                el.style.webkitAnimationTimingFunction = 'ease-out';
                el.style.webkitAnimation = 'moveback 0.3s';

                dash.style.animation= 'moveback-dash 0.3s';
                dash.style.webkitAnimationTimingFunction = 'ease-out';
                dash.style.webkitAnimation = 'moveback-dash 0.3s';

                title.style.animation= 'moveback-title 0.3s';
                title.style.webkitAnimationTimingFunction = 'ease-out';
                title.style.webkitAnimation = 'moveback-title 0.3s';

                setTimeout(function(){
                    el.style.display = 'none';
                }, 290);

                dashes.className = "";

                dash.style.left = '0';

                title.style.left = '38vw';
            });
        });

    </script>


</head>


<body>

<!-- HERE GOES MENU --

<script>
    function show_menu() {
        var el = document.getElementById("menu");

        var title = document.getElementById("title");
        var dash = document.getElementById("dash");
        var dashes = document.getElementById("alone");
        if ( el.style.display == 'none' ) {

            el.style.display = 'inline';
            el.style.animation= 'moveforward 0.3s';
            el.style.webkitAnimationTimingFunction = 'ease-in';
            el.style.webkitAnimation = 'moveforward 0.3s';

            dash.style.animation= 'moveforward-dash 0.3s';
            dash.style.webkitAnimationTimingFunction = 'ease-in';
            dash.style.webkitAnimation = 'moveforward-dash 0.3s';

            title.style.animation= 'moveforward-title 0.3s';
            title.style.webkitAnimationTimingFunction = 'ease-in';
            title.style.webkitAnimation = 'moveforward-title 0.3s';

            dashes.className = "open";

            dash.style.left = '45vw';

            title.style.left = '61vw';
        } else {

            el.style.animation= 'moveback 0.3s';
            el.style.webkitAnimationTimingFunction = 'ease-out';
            el.style.webkitAnimation = 'moveback 0.3s';

            dash.style.animation= 'moveback-dash 0.3s';
            dash.style.webkitAnimationTimingFunction = 'ease-out';
            dash.style.webkitAnimation = 'moveback-dash 0.3s';

            title.style.animation= 'moveback-title 0.3s';
            title.style.webkitAnimationTimingFunction = 'ease-out';
            title.style.webkitAnimation = 'moveback-title 0.3s';

            setTimeout(function(){
                el.style.display = 'none';
            }, 290);

            dashes.className = "";

            dash.style.left = '0';

            title.style.left = '38vw';
        }
    }
</script>
<div class="menu" id="menu" style="display: none;">
    <a href="profile.php">
        <img class="profile-image-tiny" src=" <?php if ( isset($user->image) ) {echo $user->image;} else {echo "img/space-for-avatar.png";} ?> " >
        <div class="menu_header"><?php if ( isset($user->username)) {echo $user->username;} else { echo "dev/null/";}?></div>
        <div class="menu_status">Online</div>
    </a>
    <a href="chats.php"><div class="menu_button"><img src="img/chats.svg" class="menu_image">Chats<?php if ( $user->hasPendingMessages() || $user->hasNewMessages()) { echo "<div id=notify></div>"; } ?></div></a>
    <a href="friends.php"><div class="menu_button"><img src="img/friends.svg" class="menu_image">Friends<?php if ( $user->hasPendingFriends()) { echo "<div id=notify></div>"; } ?></div></a>
    <a href="profileData.php"><div class="menu_button"><img src="img/settings.svg" class="menu_image">Settings</div></a>
    <a href="logout.php"><div class="menu_button"><img src="img/logout.svg" class="menu_image">Log out</div></a>
</div>

<!-- HERE ENDS MENU --
<!-- HERE GOES HEADER--
<div id="swipe" >


    <header style="margin-bottom: 50px;">
        <div class="dash" id="dash" onclick="show_menu()">
            <div id="alone">
                <span></span>
                <span <?php if ( $user->hasNews()) { echo "style='background: #ff1001'"; } ?> ></span>
                <span></span>
            </div>

        </div>
        <div class="header-title" id="title" style="display: block;">Profile</div>
        <div class = "search"><a href="search.php"><img class="search" src="img/search.svg"></a></div>
    </header>
    <div class="header-empty"></div>

    <!-- HERE ENDS HEADER --

    <div id = "container-for-photo">
        <div class="profile-image">
            <img class="profile-image" src=" <?php if ( isset($user->image) ) {echo $user->image;} else {echo "img/space-for-avatar.png";} ?> " >
        </div>
        <div class="status" >
            <?php echo $user->status; ?>
        </div>

        <div class="all-info">

            <?php if ( isset($user->firstname)) {echo "<div class=\"text\" >First name: ".$user->firstname."</div><br>";} ?>

            <?php if ( isset($user->lastname)) {echo "<div class=\"text\" >Last name: ".$user->lastname."</div><br>";} ?>

            <?php if ( isset($user->username)) {echo "<div class=\"text\" >username: ".$user->username."</div><br>";} ?>

            <?php if ( isset($user->gender) ) {echo "<div class=\"gender\" >".$user->gender."</div><br>";} ?>

        </div>
        <div class="detail" >
            <a href="detailInfo.php" class="detail">Detail info</a>
        </div>

    </div>

</div>
</body>
</html>
-->

<!DOCTYPE html>
<html >
<head>
    <meta charset="UTF-8">
    <title>Login</title>

    <link rel="stylesheet" href="../Styles/profile.css">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
<!--    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>-->
    <script type="text/javascript" src="JS/jquery-1.4.4.min.js"></script>
<!--    <script type="text/javascript" src="JS/jquery-3.1.1.min.js"></script>-->


</head>


<body>
<div class="background" style="background-image : url(<?php if ( isset($userForeign->image) ) {echo $userForeign->image;} else {echo "img/space-for-avatar.png";} ?>),-webkit-linear-gradient(top,rgba(125,185,232,0)0%,rgba(0,185,232,0)0%, rgba(30,87,153,1)  120%);">
    <div class="info">
        <h2><?php if ( isset($userForeign->firstname)) {echo $userForeign->firstname." ";}; if ( isset($userForeign->lastname)) { echo $userForeign->lastname;}   ?><div class="status"><?php echo $userForeign->status; ?></div></h2>
    </div>

    <div menu-pos>
        <div id="nav-icon2" onclick="openNav()">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
        </div>


        <?php
        $threeDots =  "<img onclick=\"openMaNav()\" class=\"more-actions\" src=\"../img/imgs/more-actions.png\" />";
        if ( isset($foreign)) { echo $threeDots; }
        ?>

    </div>
</div>

<div id="mySidenav" class="sidenav">
    <div class="head">

        <img class="back" src="<?php if ( isset($user->image) ) {echo $user->image;} else {echo "img/space-for-avatar.png";} ?>">

        <div class="usrname"><span class="menu-name"><?php if ( isset($user->firstname)) {echo $user->firstname." ";}; if ( isset($user->lastname)) { echo $user->lastname;}   ?><br><div class="m-status">WTF status?</div></span></div>
        <br>
        <div class="menu-pos">
            <span class="menu-status"><?php echo $user->status; ?></span>
            <hr>
        </div>
        <ul>
            <li><img class="menu-img" src="../img/imgs/chats.png"><span><a href="chats.php">Chats</a></span></li>
            <li><img class="menu-img" src="../img/imgs/friends.png"><span><a href="friends.php">Friends</a></span></li>
            <li><img class="menu-img" src="../img/imgs/blocked.png"><span>Black List</span></li>
            <li><img class="menu-img" src="../img/imgs/Settings.png"><span><a href="profileData.php">Settings</a></span><hr></li>
            <li class="logout"><img class="menu-img" src="../img/imgs/logout.png"><span><a href="logout.php">Log out</a></span></li>
        </ul>
    </div>

</div>

<?php
$srt = "<div id=\"ma-mySidenav\" class=\"ma-sidenav\">
    <a class=\"ma-closebtn\" onclick=\"closeMaNav()\">&times;</a>
    <div class=\"pos1\">
        <h1 class=\"more-actions-text\">Add to friend</h1>
        <h1 class=\"more-actions-text\">Write message</h1>
        <h1 class=\"more-actions-text\">About \"username\"</h1>
        <h1 class=\"more-actions-text\">Add to Black List</h1>
    </div>
</div>";

if ( isset($foreign) ) {
    echo $srt;
}
?>

<script>

//    $(document).ready(function(){
//        $('#nav-icon2').click(function(){
//            $(this).toggleClass('open');
//
//        });
//    });

    function openNav() {
        var k = document.getElementById("mySidenav").style.width;

            $('#nav-icon2').toggleClass('open');

        if(k == "50vw") {
            closeNav();
        }
        else {
            document.getElementById("nav-icon2").style.marginLeft = "50vw";
            document.getElementById("mySidenav").style.width = "50vw";

        }
    }

    function closeNav() {
        document.getElementById("mySidenav").style.width = "0";
        document.getElementById("nav-icon2").style.marginLeft = "4vw";
    }


    function openMaNav() {
        var k = document.getElementById("ma-mySidenav").style.height;
        console.log(k);
        if(k == "18vh") {
            closeMaNav();
        }
        else {
            document.getElementById("ma-mySidenav").style.height = "18vh";
            document.getElementById("ma-mySidenav").style.width = "50vw";

        }

    }


    function closeMaNav() {
        console.log("2");
        document.getElementById("ma-mySidenav").style.height = "0vh";
        document.getElementById("ma-mySidenav").style.width = "0vw";
    }
</script>


<script type="text/javascript" src="JS/jgestures.js"></script>
<script type="text/javascript">
    $(function(){
        $('body').bind('swiperight', function(){
            openNav();
        });
    });
    $(function(){
        $('body').bind('swipeleft', function(){
            openNav();
        });
    });
    $(function(){
        $('div').bind('swiperight', function(){
            openNav();
        });
    });
    $(function(){
        $('div').bind('swipeleft', function(){
            openNav();
        });
    });
    $(function(){
        $('img').bind('swiperight', function(){
            openNav();
        });
    });
    $(function(){
        $('img').bind('swipeleft', function(){
            openNav();
        });
    });


</script>
</body>
</html>