<!Doctype html>
<html>
<head>
    <title>Profile</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="Styles/base.css?v=<?=time();?>">
    <link rel="stylesheet" href="Styles/search.css?v=<?=time();?>">
    <style>
        ::-webkit-input-placeholder { /* WebKit browsers input color*/
            color:    black;
        }
    </style>

    <script type="text/javascript" src="JS/jquery-1.4.4.min.js"></script>
    <script type="text/javascript" src="JS/jgestures.js"></script>
    <script type="text/javascript">
        $(function(){
            $('body').bind('swiperight', function(){
                var el = document.getElementById("menu");
                var title = document.getElementById("title");
                var dash = document.getElementById("dash");
                var dashes = document.getElementById("alone");

                el.style.display = 'inline';
                el.style.animation= 'moveforward 0.3s';
                el.style.webkitAnimationTimingFunction = 'ease-in';
                el.style.webkitAnimation = 'moveforward 0.3s';

                dash.style.animation= 'moveforward-dash 0.3s';
                dash.style.webkitAnimationTimingFunction = 'ease-in';
                dash.style.webkitAnimation = 'moveforward-dash 0.3s';

                title.style.animation= 'moveforward-title 0.3s';
                title.style.webkitAnimationTimingFunction = 'ease-in';
                title.style.webkitAnimation = 'moveforward-title 0.3s';

                dashes.className = "open";

                dash.style.left = '45vw';

                title.style.left = '61vw';
            });
        });
        $(function(){
            $('body').bind('swipeleft', function(){
                var el = document.getElementById("menu");
                var title = document.getElementById("title");
                var dash = document.getElementById("dash");
                var dashes = document.getElementById("alone");

                if ( el.style.display == "none") {
                    return ;
                }

                el.style.animation= 'moveback 0.3s';
                el.style.webkitAnimationTimingFunction = 'ease-out';
                el.style.webkitAnimation = 'moveback 0.3s';

                dash.style.animation= 'moveback-dash 0.3s';
                dash.style.webkitAnimationTimingFunction = 'ease-out';
                dash.style.webkitAnimation = 'moveback-dash 0.3s';

                title.style.animation= 'moveback-title 0.3s';
                title.style.webkitAnimationTimingFunction = 'ease-out';
                title.style.webkitAnimation = 'moveback-title 0.3s';

                setTimeout(function(){
                    el.style.display = 'none';
                }, 290);

                dashes.className = "";

                dash.style.left = '0';

                title.style.left = '40vw';
            });
        });

    </script>
</head>


<body>

<!-- HERE GOES MENU -->

<script>
    function show_menu() {
        var el = document.getElementById("menu");

        var title = document.getElementById("title");
        var dash = document.getElementById("dash");
        var dashes = document.getElementById("alone");
        if ( el.style.display == 'none' ) {

            el.style.display = 'inline';
            el.style.animation= 'moveforward 0.3s';
            el.style.webkitAnimationTimingFunction = 'ease-in';
            el.style.webkitAnimation = 'moveforward 0.3s';

            dash.style.animation= 'moveforward-dash 0.3s';
            dash.style.webkitAnimationTimingFunction = 'ease-in';
            dash.style.webkitAnimation = 'moveforward-dash 0.3s';

            title.style.animation= 'moveforward-title 0.3s';
            title.style.webkitAnimationTimingFunction = 'ease-in';
            title.style.webkitAnimation = 'moveforward-title 0.3s';

            dashes.className = "open";

            dash.style.left = '45vw';

            title.style.left = '61vw';
        } else {

            el.style.animation= 'moveback 0.3s';
            el.style.webkitAnimationTimingFunction = 'ease-out';
            el.style.webkitAnimation = 'moveback 0.3s';

            dash.style.animation= 'moveback-dash 0.3s';
            dash.style.webkitAnimationTimingFunction = 'ease-out';
            dash.style.webkitAnimation = 'moveback-dash 0.3s';

            title.style.animation= 'moveback-title 0.3s';
            title.style.webkitAnimationTimingFunction = 'ease-out';
            title.style.webkitAnimation = 'moveback-title 0.3s';

            setTimeout(function(){
                el.style.display = 'none';
            }, 290);

            dashes.className = "";

            dash.style.left = '0';

            title.style.left = '40vw';
        }
    }
</script>
<div class="menu" id="menu" style="display: none;">
    <a href="profile.php">
        <img class="profile-image-tiny" src=" <?php if ( isset($user->image) ) {echo $user->image;} else {echo "img/space-for-avatar.png";} ?> " >
        <div class="menu_header"><?php if ( isset($user->username)) {echo $user->username;} else { echo "dev/null/";}?></div>
        <div class="menu_status">Online</div>
    </a>
    <a href="chats.php"><div class="menu_button"><img src="img/chats.svg" class="menu_image">Chats<?php if ( $user->hasPendingMessages() || $user->hasNewMessages()) { echo "<div id=notify></div>"; } ?></div></a>
    <a href="friends.php"><div class="menu_button"><img src="img/friends.svg" class="menu_image">Friends<?php if ( $user->hasPendingFriends()) { echo "<div id=notify></div>"; } ?></div></a>
    <a href="profileData.php"><div class="menu_button"><img src="img/settings.svg" class="menu_image">Settings</div></a>
    <a href="logout.php"><div class="menu_button"><img src="img/logout.svg" class="menu_image">Log out</div></a>
</div>

<!-- HERE ENDS MENU -->
<!-- HERE GOES HEADER-->

<header style="margin-bottom: 50px;">
    <div class="dash" id="dash" onclick="show_menu()">
        <div id="alone">
            <span></span>
            <span <?php if ( $user->hasNews()) { echo "style='background: #ff1001'"; } ?> ></span>
            <span></span>
        </div>

    </div>
    <div class="header-title" id="title" style="display: block; left: 40vw;">Search</div>
    <div class = "search"><a href="search.php"><img class="search" src="img/search.svg"></a></div>
</header>
<div class="header-empty"></div>

<!-- HERE ENDS HEADER -->

<form method="GET" action="search.php">
    <input type="text" id="search" name="search" placeholder="input search phrase" <?php if ( isset($_GET['search'])) echo "value='".$_GET['search']."'";?> >
    <input type="image" src="img/search.png?v=<?=time();?>">
</form>
<div style="display: block; width: 100%; height: 15vh;" ></div>
<?php
if ( isset($_GET['search']) && !$result ) {
    echo "<div class='no-result'>No results founded</div>";
} elseif( isset($result) ) {
    foreach ($founded as $usr) {
        $st = null;
        if ( $usr->status == "online") {
            $st = "<div id='online'></div>";
        }
        $img = ( isset($usr->image) )?  $usr->image : "/img/space-for-avatar.png";
        echo "<a href='userInfo.php?username=".$usr->username."&query=".$_GET['search']."'><div class='result'>
                    <img src='".$img."' class=\"image-tiny\" >
                    <div class=\"username\" >".$usr->username.$st." </div>
                    <div class=\"fullname\" >".$usr->getName()." </div>
              </div></a>";
    }
}
?>

</body>
</html>